create table if not exists public.designs (
 id bigint generated by default as identity primary key,
 title text default '',
 category text not null check (category in ('navvari','ari','pipe','tailoring')),
 image_url text not null,
 storage_path text not null unique,
 created_at timestamptz default now()
);
alter table public.designs enable row level security;
create policy "public view designs" on public.designs for select to anon, authenticated using (true);
create policy "logged in add designs" on public.designs for insert to authenticated with check (true);
create policy "logged in edit designs" on public.designs for update to authenticated using (true) with check (true);
create policy "logged in delete designs" on public.designs for delete to authenticated using (true);
create policy "public view images" on storage.objects for select to public using (bucket_id='designs');
create policy "logged in upload images" on storage.objects for insert to authenticated with check (bucket_id='designs');
create policy "logged in update images" on storage.objects for update to authenticated using (bucket_id='designs') with check (bucket_id='designs');
create policy "logged in delete images" on storage.objects for delete to authenticated using (bucket_id='designs');
